name: seca
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bump2version
  - graphviz
  - jupyter-book
  - keras
  - matplotlib
  - mlxtend
  - notebook
  - numpy
  - pandas
  - pip
  - pytest
  - python >=3.6,<=3.8
  - scikit-learn
  - scikit-image
  - scipy
  - tensorflow
  - tqdm
  - pip:
      - saliency
      - symspellpy
